### ISSUE TITLE
Suggestion/Request Simple MM

### ISSUE THREAD

**Issue by xispit4** [sandybradley/pyEMXMarketMaker#3]
Hello sir,

First I want to say thank you for your scripts I am still try to learn how to code :)

So far I have better working with the Deribit Simple MM script, could you do the same as Deribit script to EMX ? I just ask because so far the Simple Deribit script works like a charm and I can define/adjust my range manually without needed to adjust in the script thanks

And if possible I want to see the same to Bitmex and Bybit

**Comment by sandybradley** [comment]
Hi,

Thanks for your message. I simplified it for you as requested. See if it works and let me know.

Regarding Bitmex, I had a script running a year ago but the trading websocket is unreliable and orders are rejected during high load times, so I'm not planning to revisit that. I can do one for Bybit if you can send a donation.

Best,

Alexander

**Comment by xispit4** [comment]
I am running right now on EMX and works just fine thank you about Bybit donation I don't know how much do you expect but I am just started in this thing and don't have much so maybe later when I have more than a few sat I can make a donation :)

**Comment by sandybradley** [comment]
https://github.com/sandybradley/pyBybitMarketMaker

Happy New year. Bybit market maker above. I look forward to share in your future fortunes :)
